#!/usr/bin/python2

import serial
from serial.tools.list_ports import comports

class listSerial():
    __enabledSerialPorts = []

    def __init__(self):
        ports = comports()
        for n, (port, desc, hwid) in enumerate(sorted(comports()), 1):
           self.__enabledSerialPorts.append(port + " - " + desc)

    def __str__(self):
        enabledList = ""
        if len(self.__enabledSerialPorts) > 0:
            enabledList = "\n".join(self.__enabledSerialPorts)

        return enabledList

if __name__ == "__main__":
    lst = listSerial()
    print(lst)
