#!/usr/bin/python2

from serial.tools.list_ports import comports

class listSerial():
    __enabledSerialPorts = []

    def __init__(self):
        ports = comports()
        for n, (port, desc, hwid) in enumerate(sorted(comports()), 1):
           self.__enabledSerialPorts.append(port + " - " + desc)

    def __str__(self):
        enabledList = ""
        if self.hasComePort():
            enabledList = "\n".join(self.__enabledSerialPorts)

        return enabledList

    def hasComePort(self):
        return len(self.__enabledSerialPorts)

if __name__ == "__main__":
    lst = listSerial()
    if lst.hasComePort():
        print(lst)
